<?php
// $Id: nabuur_styles.module,v 1.1.2.4 2008/07/23 10:51:45 admin Exp $


// ---------------------------------------------------------------------------
// Panels hooks.

/**
 * Implementation of hook_panels_styles().
 */
function nabuur_styles_panels_styles() {
  return array(
    'nabuur' => array(
      'title' => t('Nabuur'),
      'description' => t('Nabuur boxed style. Edit settings to select colors'),
      'render panel' => 'nabuur_styles_style_render_panel',
      'settings form' => 'nabuur_styles_style_settings_form',
    ),
  );
}

// ---------------------------------------------------------------------------
// Panels style plugin callbacks.

/**
 * Render callback.
 *
 * @ingroup themeable
 */
function theme_nabuur_styles_style_render_panel($display, $panel_id, $panes, $settings) {
  $output = '';

  // Determine where to put the box. If empty or 'pane' around each pane. If
  // 'panel' then just around the whole panel.
  $where = empty($settings['corner_location']) ? 'pane' : $settings['corner_location'];

  $print_separator = FALSE;
  $nabuur_color = $settings['nabuur_color'];
  
  foreach ($panes as $pane_id => $pane) {
    // Add the separator if we've already displayed a pane.
    if ($print_separator) {
      $output .= "<div class=\"panel-separator $where\"></div>";
    }
    $text = theme('panels_pane', $pane, $display->content[$pane_id], $display);
    if ($text) {
      if ($where == 'pane') {
        $output .= theme('nabuur_boxed', $text,   $nabuur_color);
      }
      else {
        $output .= $text;
      }
    }

    // If we displayed a pane, this will become true; if not, it will become
    // false.
    $print_separator = (bool) $text;
  }

  if ($where == 'panel') {
    $output = theme('nabuur_boxed', $output, $nabuur_color);
  }

  return $output;
}

/**
 

// ---------------------------------------------------------------------------
// Themeing callbacks.

/**
 * @ingroup themable
 * @{
 */

/**
 * Create the HTML for our rounded corner box.
 *
 * @param $text
 *   The content of this rounded corner box.
 * @return
 *   The created HTML.
 */
function theme_nabuur_boxed($content, $nabuur_color) {
  return <<<EOF
<div class="nabuur-box $nabuur_color"><div class="nabuur-content">
  $content
</div></div>
EOF;
}

/**
 * @} End of "ingroup themeable".
 */

/**
 * Settings form callback.
 */
function nabuur_styles_style_settings_form($style_settings) {
  $form['corner_location'] = array(
    '#type' => 'select',
    '#title' => t('Box around'),
    '#options' => array(
      'pane' => t('Each pane'),
      'panel' => t('Each panel')
    ),
    '#default_value' => (isset($style_settings['corner_location'])) ? $style_settings['corner_location'] : 'ul',
    '#description' => t('Choose whether to include the box around each pane (piece of content) or panel (each column or region)'),
  );
  $form['nabuur_color'] = array(
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => array(
      'nabuur-green' => t('Nabuur green'),
      'nabuur-khaki' => t('Nabuur khaki'),
      'nabuur-beige' => t('Nabuur beige'),
      'nabuur-border' => t('Nabuur border'),
    ),
    '#default_value' => (isset($style_settings['nabuur_color'])) ? $style_settings['nabuur_color'] : 'nabuur_green',
    '#description' => t('Choose which nabuur color scheme to apply to this pane'),
  );
  return $form;
}

