<?php

$conf['custom_strings_en'] = array(

    'This question is for testing whether you are a human visitor and to prevent automated spam submissions.' => 'Enter the words below to make sure a human is trying to access this and not a computer.',
    'Location' => 'Village / City',
    'A brief description for the group details block and the group directory.' => 'Give a short description of your Village and the major problem it is facing.'

); 
