<?php // $Id: views-list-Countries.tpl.php,v 1.1.1.5 2008/07/09 12:47:26 rolf Exp $ ?>
<?php
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Fri, 05/16/2008 - 08:11
 * View: Countries
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   Countries, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $language -- 
 * $language_label -- The assigned label for $language
 * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $name -- This will display all taxonomy terms associated with the node that are members of <em>Location</em>. Note that this causes one extra query per row displayed, and might have a minor performance impact.
 * $name_label -- The assigned label for $name
 *
 * This function goes in your views-list-Countries.tpl.php file
 */
 
 
 //now we add the stylesheet...
 // drupal_add_css(path_to_theme() .'/views-list-Countries.css');
  
  ?>
<div class="view-label view-field-language">
  <?php print $language_label ?>
</div>
<div class="view-field view-data-language">
  <?php print $language?>
</div>

<div class="view-label view-field-title">
  <?php print $title_label ?>
</div>
<div class="view-field view-data-title">
  <?php print $title?>
</div>

<div class="view-label view-field-name">
  <?php print $name_label ?>
</div>
<div class="view-field view-data-name">
  <?php print $name?>
</div>
