<?php // $Id: views-teasers-village_news.tpl.php,v 1.1.1.5 2008/07/09 12:47:26 rolf Exp $ ?>
<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Sun, 05/18/2008 - 19:21
 * View: village_news
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   village_news, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $field_picture_fid -- 
 * $field_picture_fid_label -- The assigned label for $field_picture_fid
 * $field_teaser_value -- 
 * $field_teaser_value_label -- The assigned label for $field_teaser_value
 *
 * This function goes in your views-list-village_news.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-village_news.css');
  
  ?>
  <div class="top-left"><div class="top-right"><div class="bottom-right"><div class="bottom-left">
    <div class="view-label view-field-title">
      <?php print $title_label ?>
    </div>
    <div class="view-field view-data-title">
      <?php print $title?>
    </div>

    <div class="view-label view-field-field-picture-fid">
      <?php print $field_picture_fid_label ?>
    </div>
    <div class="view-field view-data-field-picture-fid">
      <?php print $field_picture_fid?>
    </div>

    <div class="view-label view-field-field-teaser-value">
      <?php print $field_teaser_value_label ?>
    </div>
    <div class="view-field view-data-field-teaser-value">
      <?php print $field_teaser_value?>
    </div>
</div></div></div></div>
