<?php // $Id: views-table-group_user_profiles.tpl.php,v 1.1.1.5 2008/07/09 12:47:26 rolf Exp $ ?>
<?php
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Thu, 05/15/2008 - 23:12
 * View: group_user_profiles
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   group_user_profiles, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $field_user_image_fid -- 
 * $field_user_image_fid_label -- The assigned label for $field_user_image_fid
 * $name -- This will display all taxonomy terms associated with the node that are members of <em>Location</em>. Note that this causes one extra query per row displayed, and might have a minor performance impact.
 * $name_label -- The assigned label for $name
 *
 * This function goes in your views-list-group_user_profiles.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-group_user_profiles.css');
  
  ?>
<div class="view-label view-field-title">
  <?php print $title_label ?>
</div>
<div class="view-field view-data-title">
  <?php print $title?>
</div>

<div class="view-label view-field-field-user-image-fid">
  <?php print $field_user_image_fid_label ?>
</div>
<div class="view-field view-data-field-user-image-fid">
  <?php print $field_user_image_fid?>
</div>

<div class="view-label view-field-name">
  <?php print $name_label ?>
</div>
<div class="view-field view-data-name">
  <?php print $name?>
</div>


?>