<?php
// $Id: geonames_search.module,v 1.1.2.2 2007/09/20 11:16:42 serosero Exp $

/**
 * @file
 * Geonames search API / by Erlend Eide, erlend(|)edesign.no
 *
 * Geonames search Service Documentation: http://www.geonames.org/export/geonames-search.html
 * API Documentation in file: geonames_search_API.txt
 *
 * IMPORTANT NOTE: The Geonames' parameter "q" must be adressed as "query"
 *
 */
 	
/**
 * Service configuration
 */  
function geonames_search_geoconfig($item = FALSE, $local = FALSE) {
  $config = array(
    'service_name'        => 'search',
    'service_full_name'   => 'GeoNames Fulltext Search',
		'description' 				=> t('Search provides names and information for geographical locations, it is probably the most comprehensive search available from GeoNames and has numereous possible parameter combinations. Note that this service allows some parameters to be arrays: country, featureclass and featurecode.'),
    'service_path'        => 'search',
    'credit_cost'         => 1,
    'result_cache_prefix' => 'seares:',
    'data_cache_prefix'   => 'seadat:',
	  'allowed_parameters'       => array(
      // our style     // geonames style
      'query'       => 'q',
      'name'        => 'name',
      'name_equals' => 'name_equals',
      'maxrows'     => 'maxRows',
      'startrow'    => 'startRow',
      'country'     => 'country',
      'admincode1'  => 'adminCode1',
      'admincode2'  => 'adminCode2',
      'admincode3'  => 'adminCode3',
      'featureclass'=> 'featureClass',
      'featurecode' => 'featureCode',
      'lang'        => 'lang',
      'style'       => 'style',
    ),
		'array_parameters' => array( // Parameters that are allowed to be arrays (or just string)
		  'country',
			'featurecode',
			'featureclass',
		),
    'required_parameters' => array( // If you have set query_defaults you should not include the parameter here
      'query', 
      'name', 
      'name_equals'
	  ),
		'required_parameters_type' => 'single',
		'query_defaults' => array(
		  'type'         => 'xml', 
			'maxrows'      => 15, 
			'featureclass' => 'p', 
			'startrow'     => 0
		),
		'pager'				   => TRUE,
		'detect_style'   => TRUE,
  );
  return ($item ? ($local ? $config[$item] : array($config['service_name'] => $config[$item])) : array($config['service_name'] => $config));
}

/**
 * Geonames search API function
 */
function geonames_search($query, $columns = FALSE) {
	// Just existing for backwards compatibility...
	return geonames_query('search', $query, $columns);
}