<?php
// $Id: geonames_neighbours.module,v 1.1.2.2 2007/09/20 11:16:42 serosero Exp $

/**
 * @file
 * Geonames Place Hierarchy Neighbours / by Erlend Eide, erlend(|)edesign.no
 * 
 * http://www.geonames.org/export/place-hierarchy.html
 */
 	
/**
 * Service configuration
 */  
function geonames_neighbours_geoconfig($item = FALSE, $local = FALSE) {
  $config = array(
    'service_name'        => 'neighbours',
    'service_full_name'   => 'Place Hierarchy: Neighbours',
		'description' 				=> t('Returns the neighbours for a given geonameId.'),
    'service_path'        => 'neighbours',
    'credit_cost'         => 1,
    'result_cache_prefix' => 'hnres:',
    'data_cache_prefix'   => 'hndat:',
	  'allowed_parameters'  => array(
      // our style     // geonames style
      'geonameid'       => 'geonameId',
			'style'           => 'style',
			'lang'            => 'lang',
    ),
    'required_parameters' => array( 
      'geonameid', 
	  ),
		'required_parameters_type' => 'single',
		'detect_style'   => TRUE,
  );
  return ($item ? ($local ? $config[$item] : array($config['service_name'] => $config[$item])) : array($config['service_name'] => $config));
}
