<?php
// $Id: geonames_gtopo30.module,v 1.1.2.2 2007/09/20 11:16:42 serosero Exp $

/**
 * @file
 * Geonames gtopo30 / by Erlend Eide, erlend(|)edesign.no
 */

/**
 * Service configuration
 */ 
function geonames_gtopo30_geoconfig($item = FALSE, $local = FALSE) {
  $config = array( 
    'service_name'             => 'gtopo30',
    'service_full_name'        => 'Elevation - GTOPO30',
    'description'              => t('GTOPO30 is a global digital elevation model (DEM) with a horizontal grid spacing of 30 arc seconds (approximately 1 kilometer). GTOPO30 was derived from several raster and vector sources of topographic information.'),
    'service_path'             => 'gtopo30',
    'credit_cost'              => 0,
    'result_cache_prefix'      => 'gtpres:',
    'data_cache_prefix'        => 'gtpdat:',
    'allowed_parameters'       => array(
       //our style  geonames style
  		 'lat'      => 'lat',
  	   'lng'      => 'lng',
			 'type'     => 'type',
	   ),
	   'required_parameters'      => array( // If you have set query_defaults you should not include the parameter here
		    'lat', 
		    'lng'
    ),
    'required_parameters_type' => 'all',
		'query_defaults' => array(
		  'type' => 'xml'
		),
	 );
  return ($item ? ($local ? $config[$item] : array($config['service_name'] => $config[$item])) : array($config['service_name'] => $config));
}
