<?php
// $Id: geonames_nearbywikipedia.module,v 1.1.2.2 2007/09/20 11:16:42 serosero Exp $

/**
 * @file
 * Geonames nearbywikipedia API / by Erlend Eide, erlend(|)edesign.no
 *
 * http://www.geonames.org/export/wikipedia-webservice.html#findNearbyWikipedia
 *
 * Parameters : 
 *   lang : language code (around 180 languages) (default = en)
 *   lat,lng, radius (in km), maxRows (default = 5),country (default = all countries)
 * or
 *   postalcode,country, radius (in Km), maxRows (default = 5)
 *
 */
 
/**
 * Service configuration
 */ 
function geonames_nearbywikipedia_geoconfig($item = FALSE, $local = FALSE) {
  $config = array(
    'service_name'         => 'nearbywikipedia',
    'service_full_name'    => 'Find nearby Wikipedia Entries (reverse geocoding)',
    'description' => 'Find nearby Wikipedia Entries (reverse geocoding)',
    'service_path'        => 'findNearbyWikipedia',
    'credit_cost'         => 2,
    'result_cache_prefix' => 'wikres:',
    'data_cache_prefix'   => 'wikdat:',
    'allowed_parameters' => array(
      //our style  geonames style
      'lat'        => 'lat',
      'lng'        => 'lng',
      'radius'     => 'radius',
      'postalcode' => 'postalcode', 				
      'lang'       => 'lang',         // Geonames default = en
      'maxrows'    => 'maxRows',      // Geonames default = 5
      'country'    => 'country',      // Geonames default = ALL
    ),
    'pager' => false,
    'required_parameters' => array( // If you have set query_defaults you should not include the parameter here
      array('lat', 'lng'),
      array('postalcode', 'country')
    ),
    'required_parameters_type' => 'all',
    'query_defaults' => array(
      'maxrows' => 15, 
      'radius'  => 10
    ),
    'columns' => array(
      'summary'      => 'summary',
      'feature'      => 'feature',
      'population'   => 'population',
      'elevation'    => 'elevation',
      'lat'          => 'lat',
      'lng'          => 'lng',
      'wikipediaurl' => 'wikipediaUrl',
      'thumbnailimg' => 'thumbnailImg',
      'lang'         => 'lang',
      'distance'     => 'distance',
    ),
  );
  return ($item ? ($local ? $config[$item] : array($config['service_name'] => $config[$item])) : array($config['service_name'] => $config));
}
