<?php
// $Id: taxonomy_image_node_display.module,v 1.1.2.2 2008/04/08 15:15:42 nancyw Exp $

/**
 *  Implementation of hook_nodeapi().
 */
function taxonomy_image_node_display_nodeapi(&$node, $op, $teaser = null, $page = null) {
  if ($op == 'view') {
    if ($teaser == true && ! variable_get('taxonomy_image_node_view_teaser', true)) {
      return;
    }
    if ($page == true && ! variable_get('taxonomy_image_node_view_page', !module_exists('taxonomy_image_blocks'))) {
      unset($node->taxonomy);
      return;
    }
    
    $valid_nodes = variable_get('taxonomy_image_node_view', array()); 
    if ($valid_nodes[$node->type]) {
      $images = array();
      $view_link = variable_get('taxonomy_image_node_view_link', true);
      foreach ($node->taxonomy as $tid => $term) {
        $image = taxonomy_image_display($tid);
        if ($view_link) {
          $image = l($image, 'taxonomy/term/'. $tid, array('class' => 'taxonomy_image_links'), null, null, false, true);
        }
        $images[] = $image;
      }
      $node->content['taxonomy_image'] = array(
        '#value' => implode("\n", $images),
        '#weight' => variable_get('taxonomy_image_node_view_weight', -5),
      );
    }
  }
}

/**
 *  Implementation of hook_form_alter().
 */
function taxonomy_image_node_display_form_alter($form_id, &$form) {
  if ($form_id == 'taxonomy_image_admin_settings') {
    $form['node_view'] = array(
      '#type' => 'fieldset',
      '#title' => t('Node Display'),
      '#weight' => 0,
      '#collapsible' => true,
      '#collapsed' => true,
      );

      $form['node_view']['taxonomy_image_node_view'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Display taxonomy images on tagged nodes'),
      '#options' => array_map('check_plain', node_get_types('names')),
      '#default_value' => variable_get('taxonomy_image_node_view', array()),
      '#description' => t('Show images in the selected content types.'),
      '#prefix' => '<div class="taxonomy_image_checkboxes">',
      '#suffix' => '</div><div class="clear-block"></div>',
      );

      $form['node_view']['taxonomy_image_node_view_teaser'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show Taxonomy Image in node teaser view'),
      '#default_value' => variable_get('taxonomy_image_node_view_teaser', true),
      );

      // If we have the blocks module, then default to false for page view.
      $form['node_view']['taxonomy_image_node_view_page'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show Taxonomy Image in node page view'),
      '#default_value' => variable_get('taxonomy_image_node_view_page', !module_exists('taxonomy_image_blocks')),
      );

      $form['node_view']['taxonomy_image_node_view_link'] = array(
      '#type' => 'checkbox',
      '#title' => t('Link displayed Taxonomy Image to taxonomy/term/n page'),
      '#default_value' => variable_get('taxonomy_image_node_view_link', true),
      '#prefix' => '<div class="clear-block"></div>',
      );

      $form['node_view']['taxonomy_image_node_view_weight'] = array(
      '#type' => 'weight',
      '#title' => t('Display weight of taxonomy images'),
      '#description' => t('Determines where the images will be displayed. Less than zero will place it before the content; greater than zero, after.'),
      '#default_value' => variable_get('taxonomy_image_node_view_weight', -5),
      );

    $form['buttons']['submit']['#weight'] = 4;
    $form['buttons']['reset']['#weight'] = 5;
  }
  return $form;
}
